services:
  - type: web
    name: LinkedArtistFrontend
    env: static
    buildCommand: npm install && npx ng build --configuration production
    staticPublishPath: dist/LinkedArtistFrontend
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
