services:
  - type: web
    name: LinkedArtistFrontend
    env: static
    buildCommand: npm install && npx ng build --configuration production
    staticPublishPath: dist/LinkedArtistFrontend
    build:
      env:
        BUN_DISABLE: "1"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
